import type { ConsoleState } from "./types.ts";

export const state: ConsoleState = {
      status: null,
      runs: [],
      selectedGoalId: "",
      selectedImprovementId: "",
      selectedSessionId: "",
      activeChatId: "",
      messages: [],
      sessions: [],
      modelOverride: "",
      audit: [],
      auditPage: 1,
      auditPagination: { page: 1, pages: 1 },
      browserTabId: "",
      selectedTaskId: "",
      taskPage: 1,
      taskPagination: { page: 1, pages: 1, total: 0, from: 0, to: 0 },
      taskSelection: new Map(),
      selectedAgentId: "",
      agents: [],
      skills: [],
      selectedSkillId: "",
      projects: [],
      selectedProjectId: "",
      memories: [],
      memoryCandidates: [],
      selectedMemoryId: "",
      memoryTab: "suggestions",
      memoryTabInitialized: false,
      memoryHealth: null,
      agentManifestDraft: null,
      experimentalRuns: [],
      experimentalActions: {},
      improvements: [],
      lastCapabilityToken: "",
      hosted: false,
      hostUser: "",
      activityTab: "overview",
      configFingerprint: "",
      configRestartRequired: false,
      config: null,
      activeView: "overview"
    };
